version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: cron
      cronjob: '0 9 1 */2 *'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    groups:
      rust-dependencies:
        patterns: ['*']
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: '0 9 1 */2 *'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns: ['*']
