install_data('org.ovenbird.Ovenbird.desktop', install_dir: get_option('datadir') / 'applications')
install_data('org.ovenbird.Ovenbird.metainfo.xml', install_dir: get_option('datadir') / 'metainfo')
install_data('org.ovenbird.Ovenbird.svg', install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps')
