// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::ffi;
use glib::GStr;

#[doc(alias = "SECRET_COLLECTION_DEFAULT")]
pub static COLLECTION_DEFAULT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::SECRET_COLLECTION_DEFAULT) };
#[doc(alias = "SECRET_COLLECTION_SESSION")]
pub static COLLECTION_SESSION: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::SECRET_COLLECTION_SESSION) };
