// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::ffi;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Schema(Shared<ffi::SecretSchema>);

    match fn {
        ref => |ptr| ffi::secret_schema_ref(ptr),
        unref => |ptr| ffi::secret_schema_unref(ptr),
        type_ => || ffi::secret_schema_get_type(),
    }
}
